settings:
  add-owner-assignee: true
  process-closed-issues: true
  remove-labels: true
  remove-keyword-labels: true
  close-issues: true

title-keyword-labels:
  in-progress: ["WiP"]
  chore: ["chore"]
  bugfix: ["bug","bugfix","fix"]
  feature: ["feature"]
  enhancement: ["enhancement"]
