name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Main Checkout
      with:
        persist-credentials: false
        fetch-depth: 0
        path: main

    - uses: actions/checkout@v2
      name: Secondary Checkout
      with:
        repository: sabuto/bot-test2
        path: secondary
        persist-credentials: false
        fetch-depth: 0

    - name: move file to other repo
      run: \cp -Rv main/.github/sabubot.yml secondary/.github/sabubot.yml

    - name: commit to local
      run: |
        cd secondary
        git config --local user.email "robe_dunne@hotmail.com"
        git config --local user.name "sabuto"
        git add .
        git commit -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PSA }}
        repository: sabuto/bot-test2
        directory: secondary
