name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Main Checkout

    - name: Secondary Checkout
      run: |
      cd ../
      git clone git@github.com/sabuto/bot-test2
      
    - name: do ls etc
      run: |
        pwd
        ls
        cd ../
        ls
